version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    networks:
      - caddy
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    restart: unless-stopped
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    networks:
      - caddy
    stdin_open: true
    tty: true
    volumes:
      - ./caddy:/config
      - /etc/localtime:/etc/localtime:ro
    entrypoint: /usr/bin/caddy run --adapter caddyfile --config /config/Caddyfile
    depends_on:
      - cloudflared
  nginx:
    image: nginx
    networks:
      - caddy
    depends_on:
      - caddy
  httpd:
    image: httpd
    networks:
      - caddy
    depends_on:
      - caddy
networks:
  caddy:


